name: CI - Build & Push to ECR

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    permissions:
      id-token: write
      contents: write

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Node CI
      - name: Node CI
        uses: ./.github/actions/node-ci
        with:
          node-version: "20.16.0"

      # Debug ARN
      - name: Debug resolved ARN
        run: echo "Resolved ARN - arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/air-max-270-github-actions-dev"

      # Configure AWS credentials (OIDC)
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/air-max-270-github-actions-dev
          aws-region: ${{ vars.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/air-max-270/landing-dev:${{ github.sha }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/air-max-270/landing-dev:latest
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      # Save image reference for later jobs schedule
      - name: Set image env variable
        run: echo "IMAGE=$ECR_URI:$IMAGE_TAG" >> $GITHUB_ENV
